### ISSUE TITLE
Termination warning due to background task

### ISSUE THREAD

**Issue by nezhyborets** [amplitude/Amplitude-Swift#101]
## Expected Behavior

Background task configured correctly

## Current Behavior

I receive such message in console
```
Background Task 13 119 ("amplitude"), was created over 30 seconds ago.
In applications running in the background, this creates a risk of termination.
Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```
## Possible Solution

Not sure, probably call `UIApplication.endBackgroundTask(_:)` when task is completed

## Steps to Reproduce
 

Just run the app, the logs will come soon. Sample log:
[Amplitude.zip](https://github.com/amplitude/Amplitude-Swift/files/13461713/Amplitude.zip)
I believe there was no such problem in Amplitude-iOS SDK, only in Swift one.

## Environment
- SDK Version:  Amplitude-Swift 1.1.0
- OS Info:  iOS 17.1.1, iPhone 13

**Comment by liuyang1520** [comment]
Hi @nezhyborets ,

Thanks for reporting this! I have done the following investigations:
- The code does run `endBackgroundTask` in the [expirationHandler](https://github.com/amplitude/Amplitude-Swift/blob/353b334924d05c67a85d403584a065999a778c2b/Sources/Amplitude/Plugins/Vendors/AppUtil.swift#L73) and after [task completion](https://github.com/amplitude/Amplitude-Swift/blob/353b334924d05c67a85d403584a065999a778c2b/Sources/Amplitude/Utilities/HttpClient.swift#L41-L46).
- I am not able to see that log when running the UI example app with iPhone 15 and iso 17.0.1 locally.

Could you provide a sample app that can trigger these logs? Also, could you enable the debug mode or at least the log mode so we can get more useful output like [this](https://github.com/amplitude/Amplitude-Swift/blob/353b334924d05c67a85d403584a065999a778c2b/Sources/Amplitude/Utilities/EventPipeline.swift#L48) (I didn't see this info in the sample log above)?

Thanks

**Comment by perrin-salus** [comment]
I've also been experiencing this issue, which appears to be part of an infinite loop that causes high CPU and memory leaking making the app unusable and eventually crashing.

I initialize with this code in a global singleton:
```swift
let amplitude = Amplitude(configuration: Configuration(
    apiKey: "<token here>",
    logLevel: .DEBUG,
    defaultTracking: .ALL
))
```

After running for about 30 seconds, I see a bunch of logs start to appear. First I see this:
```
Log: Start flushing 1 events
Log: Cleaned up 0 non-running uploads.
Log: Cleaned up 1 non-running uploads.
Log: Cleaned up 2 non-running uploads.
Log: Start flushing 30 events
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
2 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
2 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
1 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
2 log/signpost messages lost due to high rates in live mode recording. To guarantee delivery of all logs, set IDELogRedirectionPolicy to oslogToStdio in the environment of the executable.
Log: Cleaned up 15 non-running uploads.
```
This continues for a while printing at high frequency with different numbers of non-running uploads cleaned up each time.

It seems to change what logs are being printed every once in a while. Sometimes it stops the log/signpost messages and just shows the flushing/cleaning logs:
```
Log: Start flushing 30 events
Log: Cleaned up 0 non-running uploads.
Log: Cleaned up 0 non-running uploads.
Log: Start flushing 30 events
Log: Cleaned up 74 non-running uploads.
Log: Cleaned up 0 non-running uploads.
Log: Start flushing 30 events
Log: Cleaned up 5 non-running uploads.
Log: Cleaned up 0 non-running uploads.
Log: Start flushing 30 events
Log: Cleaned up 0 non-running uploads.
Log: Cleaned up 0 non-running uploads.
Log: Start flushing 30 events
Log: Cleaned up 49 non-running uploads.
Log: Cleaned up 0 non-running uploads.
```

Other times it begins showing the background task logs that are noted above:
```
Background Task 1,542 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,543 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,544 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,545 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,546 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,547 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,548 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,549 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,550 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,551 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
Background Task 1,552 ("amplitude"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```

In the device files (running on iPhone 15 Pro simulator) I can see a large number of files created:
<img width="606" alt="Screenshot 2023-12-12 at 11 25 40" src="https://github.com/amplitude/Amplitude-Swift/assets/136731634/e20478d6-d8ba-4a90-a622-7482775cda77">

These files appear to be full of events which are older than the files (2+ weeks). My hunch is that it is somehow trying and failing to upload these old events, which is causing an infinite loop. I do not see any logs that would indicate why the failures are occurring; I have confirmed that my token is correct, and the device is connected to the internet.

This is occurring both on the simulator mentioned above, as well as my physical device (iPhone 14 Pro).

Hopefully this is helpful in debugging! Please ping me if you need additional details 🙂

**Comment by liuyang1520** [comment]
Hi @perrin-salus, thanks for sharing more information here!

I just tried with the exact same configure as you provided, running it in our test example app, and manually firing hundreds of events. The logs and app are still fine to me.

Since there are a lot of pending events in your app, I am curious how frequently does a `track` call happen in your app? It might be that your app is generating way more events than our default flush queue interval 30 event or 30 seconds. Could you also try to:
- increase the `flushQueueSize` value?
- use batch mode, with `useBatch`

Here are more detailed configurations: https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#configuration.

As for the 400 error, I am not sure why you got that, it might not be from iOS source. I don't have more insights unfortunately. But the iOS SDK should not retry on this as [400 doesn’t belong to the retry bucket](https://github.com/amplitude/Amplitude-Swift/blob/353b334924d05c67a85d403584a065999a778c2b/Sources/Amplitude/Utilities/PersistentStorageResponseHandler.swift#L50-L55), so I think this is not related.

Thanks!

**Comment by perrinswanson** [comment]
Hi @liuyang1520 thanks for the quick reply!

At the moment we don't call track manual events at all, aside from a couple times sending up a quick "Hello World" to make sure it was working when I was first setting it up. Typically I have been running it with `defaultTracking: .ALL` to get events for screen views, sessions, and app lifecycle.

After some more testing on my end, I've managed to partially resolved the issue and figured out why the requests have been failing. Searching through the configuration you linked, I noticed one particular setting that I hadn't previously given much thought: `minIdLength`. I've been testing so far on a development environment with only a few users - my usual test account is ID 3 (we are tracking users by their numeric ID rather than email address, which it seems is not the default expected use case). In the code, the default value for `minIdLength` is `nil`, which I assumed meant there is no minimum length. However, according to the documentation, the default value is actually `5` - I assume nil values get replaced with 5 somewhere internally. I updated my configuration to use `1` for the minimum length, and noticed improvements.

On a freshly-installed simulator, no errors occurred and all events were sent successfully. On the simulator which was previously having the looping issue, I noticed CPU spikes occurring every 30 seconds as it attempted to upload events, but calmed down again rather than staying high indefinitely. In the console I still noticed some of the log/signpost messages mixed in with the flush/cleanup logs, however the background task warnings no longer occurred. On the Ingestion Debugger I also noticed the errors changed from 400 to 429 - too many requests.

![Screenshot 2023-12-13 at 09 14 39](https://github.com/amplitude/Amplitude-Swift/assets/7077422/5ceb789b-7981-4468-bc1f-9b2acf2d4e92)

<img width="1515" alt="Screenshot 2023-12-13 at 09 26 23" src="https://github.com/amplitude/Amplitude-Swift/assets/7077422/1776adb5-caec-4ea1-8f50-dfccd68c802d">

I then enabled `useBatch` as suggested and tried again, and after 1.5 CPU spikes it calmed down and finished uploading all the events. The device now runs fine again with no more issues.

![Screenshot 2023-12-13 at 09 50 35](https://github.com/amplitude/Amplitude-Swift/assets/7077422/2e5f07f4-76f2-4e2e-9dde-3b1b826a6004)

Overall my observations are:
1. It can be fairly easy to misconfigure the settings, with the default value in the code being misleading compared to the documentation, and no clear indication that the configuration is wrong
2. Some unknown bug can cause a huge backlog of events to occur. Unfortunately I have no idea what could be causing this, though it happened multiple times on both the simulator and physical device
3. A combination of the above leads to infinite looping as it attempts to upload events unsuccessfully, causing high CPU, high memory usage, and the background task termination warning that this issue originally reported

Now that I have the configuration issue sorted, I'm hopeful that I should be able to continue deploying even without knowing the cause of the bug. It would still be great if any progress can be made on figuring that out, and maybe something could be done to avoid everything exploding in the case of misconfiguration.

One last thing, I did save a couple of the log files before everything was uploaded. I'm not sure if the events in them will be useful for debugging at all, but I'll provide them just in case:

[9271](https://github.com/amplitude/Amplitude-Swift/files/13664473/Amplitude.1.json)
[9260](https://github.com/amplitude/Amplitude-Swift/files/13664474/Amplitude.2.json)

Thanks again!

**Comment by liuyang1520** [comment]
@perrinswanson , thank you very much for providing these details! Glad that it finally got sorted out!

In terms of the configuration, as the source code is open to read, also we have the [configuration documentation](https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#configuration), feel free to read the doc at first, as the default value in the source code might get overwritten in SDK pipeline/timeline/plugins. E.g., the `minIdLength` is 5 by default (mentioned in the doc), but this value is actually defined by our [ingestion pipeline API](https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/#device-ids-and-user-ids-minimum-length).

As for debugging the payload, refer to this [section](https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#troubleshooting-and-debugging), for example, you can add a simple callback like this to see the actual response:
```swift
configuration: Configuration(
    apiKey: "xxx",
    logLevel: LogLevelEnum.DEBUG,
    callback: { (event: BaseEvent, code: Int, message: String) -> Void in
        print("eventcallback: \(event), code: \(code), message: \(message)")
    },
    defaultTracking: .ALL
)
```

Thank you again for supporting Amplitude!
