### ISSUE TITLE
0.3.1 not sending any events

### ISSUE THREAD

**Issue by kelvinharron** [amplitude/Amplitude-Swift#38]
## Expected Behavior
Events from app behaviour should display on amplitude platform.

## Current Behavior
No events are showing after upgrading to AmplitudeSwift 0.3.1.

## Possible Solution
Downgrade to AmplitudeSwift 0.3.0

## Steps to Reproduce
1. Bumped podfile dependency to 0.3.1.
2. Built and ran new developer build of the app.
3. Navigated through app to generate events (which worked previously on 0.3.0).
4. No events are showing on Amplitude Platform, but they did show when using AmplitudeSwift 0.3.0.

Is is possible [this is the cause](https://github.com/amplitude/Amplitude-Swift/pull/34)? I did try specifying the SDK with the following but this didn't resolve it.

```
// 0.3.0 and 0.3.1
Configuration(apiKey: amplitudeDeveloperApiKey, logLevel: LogLevelEnum.DEBUG, serverZone: ServerZone.EU)

// 0.3.1 with tweak
Configuration(apiKey: amplitudeDeveloperApiKey, logLevel: LogLevelEnum.DEBUG, serverZone: ServerZone.EU, serverUrl: Constants.EU_DEFAULT_API_HOST)
```

## Environment
- SDK Version: 0.3.1
- OS Info: iOS 16.2

**Comment by liuyang1520** [comment]
Hi @kelvinharron ,

Thanks for supporting Amplitude!

I just tried the [example](https://github.com/amplitude/Amplitude-Swift/tree/main/Examples/AmplitudeSwiftUIExample) with following configure, the events are fired and showing up in Amplitude:

```
configuration: Configuration(apiKey: "xxx", logLevel: LogLevelEnum.DEBUG, serverZone: ServerZone.EU)
```

I don't think it is related to that change. Could you add the callback to check what is the response?
```
        configuration: Configuration(
            apiKey: "xxx",
            logLevel: LogLevelEnum.DEBUG,
            callback: { (event: BaseEvent, code: Int, message: String) -> Void in
                print("eventcallback: \(event), code: \(code), message: \(message)")
            },
            serverZone: ServerZone.EU,
        )
```

Thanks!

**Comment by liuyang1520** [comment]
Hi @kelvinharron ,

Good to hear that you figured it out!

The default `serverZone` value is US, as I notice you mentioned `ServerZone.EU` in the steps to produce, so I tested it with my EU Amplitude project. This is the expected behavior that after setting EU, it will send to the EU endpoint, and the new version (0.3.1) fixed a bug to make this `ServerZone.EU` actual work.

If you need to use the EU server, you need to create a project in the EU endpoint as you mentioned above, the API key is not shared across projects. I am not sure about the process of moving to EU, contacting customer support would definitely be helpful on this.

Closing this now, feel free to leave comment if you have more questions, thanks again for supporting Amplitude!

**Comment by kelvinharron** [comment]
Thanks again for the support @liuyang1520 !
