### ISSUE TITLE
Is there a way to clear persisted events?

### ISSUE THREAD

**Issue by El-Fitz** [amplitude/Amplitude-Swift#77]
## Summary

Following a @StateObject update infinite loop that lead my SwiftUI View to update what seems to be several thousand times per second, and even though the issue had been resolved, I would regularly randomly end up with significant sustained (> 5 minutes) spikes in memory (> 1.5GB) and CPU (~190%) usage.

Investigating memory allocations & the memory graph lead me to `PersistentStorageResponseHandler` and `HTTPClient`. I imagine my little mistake must have generated a huge amount of locally persisted unsent events.

Because of that, every time I would launch the app, the Amplitude SDK would, at some point, start trying to upload these events.

I could confirm the origin by disabling the Amplitude SDK, and deleting and re-running the app before re-enabling the SDK solved my issue. But that wouldn't be a solution for end-users.

Is there a way to determine the volume of persisted events and to clean them up if necessary?

**Comment by yuhao900914** [comment]
Hi @El-Fitz,

Thank you for using Amplitude.

Currently, there isn't a direct method to clean up all the unsent events. This is because we aim to ensure our customers don't inadvertently lose any event data. The SDK will only drop an event if it exceeds the maxRetries limit or if the event isn't retryable.

However, we offer several configurations you can tweak to adjust when events are flushed. Please refer to the [configuration section](https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#configuration) for details on flushIntervalMillis, flushQueueSize, and flushEventsOnClose configurations.

Additionally, all the events are saved in files within this [directory](https://github.com/amplitude/Amplitude-Swift/blob/main/Sources/Amplitude/Storages/PersistentStorage.swift#L212). You can navigate directly to that directory to delete the event files if needed.
